# testbench
test_post_sim.v

# netlist generated by P&R
../../icc/post_layout/CHIP_layout.v

# Logic Gate models
-v /usr/cadtool/SAED32_EDK/lib/stdcell_hvt/verilog/saed32nm_hvt.v

# SRAM model
sram_model/sram_256x32b.v
sram_model/sram_16x128b.v

+define+POSTSIM
+access+r
