# testbench
test_gate_top.v

# netlist generated by Design Compiler
../../syn/netlist/tpu_top_syn.v

# Logic Gate models
-v /usr/cadtool/cad/synopsys/SAED32_EDK/lib/stdcell_hvt/verilog/saed32nm_hvt.v

# SRAM model
sram_model/sram_256x32b.v
sram_model/sram_64x512b.v

+define+GATESIM
+access+r
