set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 3.000 -nets VDD -layer 17 -width 4.000 -start_low_ends coordinate  -start_low_ends_coordinate 1.000 -start_high_ends coordinate  -start_high_ends_coordinate 448.064 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 445.000 -nets VDD -layer 17 -width 4.000 -start_low_ends coordinate  -start_low_ends_coordinate 1.000 -start_high_ends coordinate  -start_high_ends_coordinate 448.064 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 446.064 -nets VDD -layer 19 -width 4.000 -start_low_ends coordinate  -start_low_ends_coordinate 1.000 -start_high_ends coordinate  -start_high_ends_coordinate 447.000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 3.000 -nets VDD -layer 19 -width 4.000 -start_low_ends coordinate  -start_low_ends_coordinate 1.000 -start_high_ends coordinate  -start_high_ends_coordinate 447.000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 7.730 -nets VSS -layer 17 -width 4.000 -start_low_ends coordinate  -start_low_ends_coordinate 5.730 -start_high_ends coordinate  -start_high_ends_coordinate 443.334 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 440.270 -nets VSS -layer 17 -width 4.000 -start_low_ends coordinate  -start_low_ends_coordinate 5.730 -start_high_ends coordinate  -start_high_ends_coordinate 443.334 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 441.334 -nets VSS -layer 19 -width 4.000 -start_low_ends coordinate  -start_low_ends_coordinate 5.730 -start_high_ends coordinate  -start_high_ends_coordinate 442.270 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 7.730 -nets VSS -layer 19 -width 4.000 -start_low_ends coordinate  -start_low_ends_coordinate 5.730 -start_high_ends coordinate  -start_high_ends_coordinate 442.270 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal4 straps for net VDD
create_power_straps  -direction horizontal  -start_at 222.532 -nets VDD  -layer 17 -width 2.000 -pitch_within_group 213.000 -start_low_ends coordinate  -start_low_ends_coordinate 1.000 -start_high_ends coordinate  -start_high_ends_coordinate 448.064 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal4 straps for net VSS
create_power_straps  -direction horizontal  -start_at 225.164 -nets VSS  -layer 17 -width 2.000 -pitch_within_group 213.000 -start_low_ends coordinate  -start_low_ends_coordinate 5.730 -start_high_ends coordinate  -start_high_ends_coordinate 443.334 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VDD
create_power_straps  -direction vertical  -start_at 116.436 -nets VDD  -layer 19 -width 2.000 -pitch_within_group 106.766 -start_low_ends coordinate  -start_low_ends_coordinate 1.000 -start_high_ends coordinate  -start_high_ends_coordinate 447.000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 223.140 -nets VDD  -layer 19 -width 2.000 -pitch_within_group 106.766 -start_low_ends coordinate  -start_low_ends_coordinate 1.000 -start_high_ends coordinate  -start_high_ends_coordinate 447.000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 329.844 -nets VDD  -layer 19 -width 2.000 -pitch_within_group 106.766 -start_low_ends coordinate  -start_low_ends_coordinate 1.000 -start_high_ends coordinate  -start_high_ends_coordinate 447.000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VSS
create_power_straps  -direction vertical  -start_at 119.068 -nets VSS  -layer 19 -width 2.000 -pitch_within_group 106.766 -start_low_ends coordinate  -start_low_ends_coordinate 5.730 -start_high_ends coordinate  -start_high_ends_coordinate 442.270 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 225.772 -nets VSS  -layer 19 -width 2.000 -pitch_within_group 106.766 -start_low_ends coordinate  -start_low_ends_coordinate 5.730 -start_high_ends coordinate  -start_high_ends_coordinate 442.270 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 332.476 -nets VSS  -layer 19 -width 2.000 -pitch_within_group 106.766 -start_low_ends coordinate  -start_low_ends_coordinate 5.730 -start_high_ends coordinate  -start_high_ends_coordinate 442.270 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
